import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
import Services from "../sections/services/services";
import Purpose from "../sections/purpose/purpose";
import Projects from "../sections/projects/projects";
import Testimonial from "../sections/testimonial/testimonial";
import SignUpForm from "../sections/signUpForm/signUpForm";
import { bannerData, ourServicesData } from "../utils/indexPageData";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner
          title={bannerData.title}
          description={bannerData.description}
          buttonText={bannerData.buttonText}
          bannerImage={bannerData.bannerImage}
        ></Banner>
        <Services
          title={ourServicesData.title}
          description={ourServicesData.description}
          buttonText={ourServicesData.buttonText}
        ></Services>
        <Purpose></Purpose>
        <Projects></Projects>
        <Testimonial></Testimonial>
        <SignUpForm></SignUpForm>
      </div>
    </>
  );
}
